services: 
  api:
      build: .
      ports:
            - 80:80
      environment:
            DB_NAME: appdb
            DB_USER: root
            DB_PASSWORD: toor
            DB_HOST: db 
            DB_PORT: 3306
      env_file:
            - ./.env
      volumes:
            - .:/src 
      depends_on:
            - db 
  
  db:
      image: mysql:8
      environment: 
            MYSQL_DATABASE: appdb 
            MYSQL_ROOT_PASSWORD: toor 
      volumes:
            - data:/var/lib/mysql

volumes:
  data: